### ISSUE TITLE
[Error]: error trying to discover devices: invalid urn supplied

### ISSUE THREAD

**Issue by s7x** [reflix/rupnpc#1]
Hi there!

The following error is appearing when I try to run the tool:

```
Error: error trying to discover devices: invalid urn supplied
```

**Command**:

```bash
rupnpc -f "{name} {url}"
```

![image](https://github.com/reflix/rupnpc/assets/33422344/8f33da76-5200-4707-bb6d-ffb5bc610267)

Cheers!

**Comment by reflix** [comment]
Nice catch!

The underlying library seems to have a problem parsing the URN returned by the device and signals this error. The code fails to handle the error, as there is _no_ error handling at all.

We may not provide useful information about the device, but, at least, we might not crash.

**Comment by reflix** [comment]
You may test whether the issue persists in 17746f4192bd19414e0efbec6995bd34b75fcd2c
